# Use this for mapping to external links
extlinks = {
    'incf_collection': ('https://training.incf.org/collection/neurodata-without-borders-neurophysiology-nwbn/%s', '%s'),
    'nwb_extension_git': ('https://github.com/nwb-extensions/%s', '%s'),
    'ndx-catalog': ('https://nwb-extensions.github.io/%s', '%s'),
    'pynwb-issue': ('https://github.com/NeurodataWithoutBorders/pynwb/issues/%s', 'pynwb#%s'),
    'nwb2-biorxiv': ('https://www.biorxiv.org/content/10.1101/523035v1/%s',None),
    'nwb2-biorxiv-pdf': ('https://www.biorxiv.org/content/biorxiv/early/2019/01/17/523035.full.pdf%s', None),
    'allen-cell-type-atlas': ('http://celltypes.brain-map.org/%s', '%s'),
    'api-python': ('https://neurodatawithoutborders.github.io/api-python/build/html/api_usage.html%s', '%s'),
    'pynwb-src': ('https://github.com/NeurodataWithoutBorders/pynwb/%s', '%s'),
    'pynwb-docs': ('https://pynwb.readthedocs.io/en/stable/%s', '%s'),
    'hdmf-docs': ('https://hdmf.readthedocs.io/en/stable/%s', '%s'),
    'hdmf-src': ('https://github.com/hdmf-dev/hdmf/%s', '%s'),
    'hdmf-specification-language': ('https://hdmf-schema-language.readthedocs.io/en/latest/%s', '%s'),
    'matnwb-src': ('https://github.com/NeurodataWithoutBorders/matnwb/%s', '%s'),
    'matnwb-docs': ('https://neurodatawithoutborders.github.io/matnwb/%s', '%s'),
    'neuroconv-docs': ('https://neuroconv.readthedocs.io/en/main/%s', '%s'),
    'neuroconv-src': ('https://github.com/catalystneuro/neuroconv/%s', '%s'),
    'nwbinspector-docs': ('https://nwbinspector.readthedocs.io/en/dev/%s', '%s'),
    'ndx-template-docs': ('https://github.com/nwb-extensions/ndx-template/%s', '%s'),
    'ndx-template-src': ('https://github.com/nwb-extensions/ndx-template/%s', '%s'),
    'ndx-catalog-github-org': ('https://github.com/nwb-extensions/%s', '%s'),
    'hdmf-docutils-docs': ('https://github.com/hdmf-dev/hdmf-docutils/%s', '%s'),
    'hdmf-docutils-src': ('https://github.com/hdmf-dev/hdmf-docutils/%s', '%s'),
    'nwb-schema-language-docs': ('https://schema-language.readthedocs.io/en/latest/%s', '%s'),
    'nwb-storage-docs': ('https://nwb-storage.readthedocs.io/en/latest/%s', '%s'),
    'nwb-schema-docs': ('https://nwb-schema.readthedocs.io/en/latest/%s', '%s'),
    'nwb-schema-release-notes':('http://nwb-schema.readthedocs.io/en/latest/format_release_notes.html%s', '%s'),
    'nwb-schema-src': ('https://github.com/NeurodataWithoutBorders/nwb-schema/%s', '%s'),
    'hdmf-common-schema-docs': ('https://hdmf-common-schema.readthedocs.io/en/stable/%s', '%s'),
    'hdmf-common-schema-src': ('https://github.com/hdmf-dev/hdmf-common-schema/%s', '%s'),
    'hdmf-z-docs': ('https://hdmf-zarr.readthedocs.io/en/latest/%s', '%s'),
    'hdmf-z-src': ('https://github.com/hdmf-dev/hdmf-zarr/%s','%s'),
    'nwb-github-org': ('https://github.com/NeurodataWithoutBorders/%s', '%s'),
    'hdmf-github-org': ('https://github.com/hdmf-dev/%s', '%s'),
    'nwb-widgets-docs': ('https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/%s', '%s'),
    'nwb-widgets-src': ('https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets/%s', '%s'),
    'caiman-docs': ('https://caiman.readthedocs.io/en/master/%s', '%s'),
    'hdf5': ('https://www.hdfgroup.org/solutions/hdf5/%s', '%s'),
    'zarr': ('https://zarr.readthedocs.io/en/stable/%s', '%s'),
    'nix': ('https://g-node.github.io/nix/%s', '%s'),
    'bids': ('https://bids.neuroimaging.io/%s', '%s'),
    'dandi': ('https://dandiarchive.org/%s', '%s'),
    'nwb-overview-src': ('https://github.com/NeurodataWithoutBorders/nwb-overview/%s', '%s'),
    'nwb-main': ('https://www.nwb.org/%s', '%s'),
    'nwb-helpdesk': ('https://github.com/dandi/helpdesk/discussions/%s', '%s'),
    # 'nwb-mailing-list': (r'http://visitor.r20.constantcontact.com/manage/optin?v=001nQUq2GTjwCjZxK_V2'
    #                      r'-6RLElLJO1HMVtoNLJ-wGyDCukZQZxu2AFJmNh6NS0_lGMsWc2w9hZpeNn74HuWdv5RtLX9qX0o0Hy1P0hOgMrkm2NoGAX3VoY25wx8HAtIZwredcCuM0nCUGodpvoaue3SzQ%3D%3D', '%s'),
    'datajoint': ('https://www.datajoint.org/%s', '%s'),
    'datajoint-elements': ('https://www.datajoint.com/elements/%s', '%s'),
    'openscope-databook': ('https://alleninstitute.github.io/openscope_databook/%s', '%s'),
    'openscope-project': ('https://alleninstitute.org/what-we-do/brain-science/research/mindscope-program/openscope/%s', '%s'),
    'mindscope-program': ('https://alleninstitute.org/what-we-do/brain-science/research/mindscope-program/%s', '%s'),
    'jupyter-book': ('https://jupyterbook.org/en/stable/%s', '%s'),
}

# Use this for mapping for links to commonly used documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
    'h5py': ('https://docs.h5py.org/en/latest/', None),
    'hdmf': ('https://hdmf.readthedocs.io/en/stable/', None),
    'hdmf-z': ('https://hdmf-zarr.readthedocs.io/en/latest/', None),
    'pynwb': ('https://pynwb.readthedocs.io/en/stable/', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
    'neuroconv': ('https://neuroconv.readthedocs.io/en/main/', None),
    "nwb-schema": ("https://nwb-schema.readthedocs.io/en/latest/", None),
    "hdmf-common-schema": ("https://hdmf-common-schema.readthedocs.io/en/stable/", None),
}
