# Use this for mapping to external links
extlinks = {
    'incf_collection': ('https://training.incf.org/collection/neurodata-without-borders-neurophysiology-nwbn', ''),
    'nwb_extension_git': ('https://github.com/nwb-extensions/%s', ''),
    'ndx-catalog': ('https://nwb-extensions.github.io/', ''),
    'pynwb-issue': ('https://github.com/NeurodataWithoutBorders/pynwb/issues/%s', 'pynwb#%s'),
    'nwb2-biorxiv': ('https://www.biorxiv.org/content/10.1101/523035v1',''),
    'nwb2-biorxiv-pdf': ('https://www.biorxiv.org/content/biorxiv/early/2019/01/17/523035.full.pdf',''),
    'allen-cell-type-atlas': ('http://celltypes.brain-map.org/', ''),
    'api-python': ('https://neurodatawithoutborders.github.io/api-python/build/html/api_usage.html', ''),
    'pynwb-src': ('https://github.com/NeurodataWithoutBorders/pynwb/', ''),
    'pynwb-docs': ('https://pynwb.readthedocs.io/en/stable/', '%s'),
    'hdmf-docs': ('https://hdmf.readthedocs.io/en/stable/', ''),
    'hdmf-src': ('https://github.com/hdmf-dev/hdmf', ''),
    'hdmf-specification-language': ('https://hdmf-schema-language.readthedocs.io/en/latest/', ''),
    'matnwb-src': ('https://github.com/NeurodataWithoutBorders/matnwb/', ''),
    'matnwb-docs': ('https://neurodatawithoutborders.github.io/matnwb/', ''),
    'nwbconversiontool-docs': ('https://nwb-conversion-tools.readthedocs.io/en/main/', ''),
    'nwbconversiontool-src': ('https://github.com/catalystneuro/nwb-conversion-tools/', ''),
    'nwbinspector-docs': ('https://nwbinspector.readthedocs.io/en/dev/', ''),
    'ndx-template-docs': ('https://github.com/nwb-extensions/ndx-template', ''),
    'ndx-template-src': ('https://github.com/nwb-extensions/ndx-template', ''),
    'ndx-catalog': ('https://nwb-extensions.github.io/', ''),
    'ndx-catalog-github-org': ('https://github.com/nwb-extensions/', ''),
    'hdmf-docutils-docs': ('https://github.com/hdmf-dev/hdmf-docutils', ''),
    'hdmf-docutils-src': ('https://github.com/hdmf-dev/hdmf-docutils', ''),
    'nwb-schema-language-docs': ('https://schema-language.readthedocs.io/en/latest/', ''),
    'nwb-schema-docs': ('https://nwb-schema.readthedocs.io/en/latest/', ''),
    'nwb-schema-release-notes':('http://nwb-schema.readthedocs.io/en/latest/format_release_notes.html', ''),
    'nwb-schema-src': ('https://github.com/NeurodataWithoutBorders/nwb-schema', ''),
    'hdmf-common-schema-docs': ('https://hdmf-common-schema.readthedocs.io/en/stable/', ''),
    'hdmf-common-schema-src': ('https://github.com/hdmf-dev/hdmf-common-schema', ''),
    'nwb-github-org': ('https://github.com/NeurodataWithoutBorders', ''),
    'hdmf-github-org': ('https://github.com/hdmf-dev', ''),
    'nwb-widgets-docs': ('https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets', ''),
    'nwb-widgets-src': ('https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets', ''),
    'caiman-docs': ('https://caiman.readthedocs.io/en/master/', ''),
    'hdf5': ('https://www.hdfgroup.org/solutions/hdf5/',''),
    'zarr': ('https://zarr.readthedocs.io/en/stable/', ''),
    'nix': ('https://g-node.github.io/nix/', ''),
    'bids': ('https://bids.neuroimaging.io/', ''),
    'dandi': ('https://dandiarchive.org/', ''),
    'nwb-overview-src': ('https://github.com/NeurodataWithoutBorders/nwb-overview', ''),
    'nwb-main': ('https://www.nwb.org/', ''),
    'nwb-helpdesk': ('https://github.com/dandi/helpdesk/discussions', ''),
    'nwb-mailing-list': ('http://visitor.r20.constantcontact.com/manage/optin?v=001nQUq2GTjwCjZxK_V2'
                         '-6RLElLJO1HMVtoNLJ-wGyDCukZQZxu2AFJmNh6NS0_lGMsWc2w9hZpeNn74HuWdv5RtLX9qX0o0Hy1P0hOgMrkm2NoGAX3VoY25wx8HAtIZwredcCuM0nCUGodpvoaue3SzQ%3D%3D', ''),
}

# Use this for mapping for links to commonly used documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
    'h5py': ('https://docs.h5py.org/en/latest/', None),
    'hdmf': ('https://hdmf.readthedocs.io/en/latest/', None),
    'pynwb': ('https://pynwb.readthedocs.io/en/stable/', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
    'nct': ('https://nwb-conversion-tools.readthedocs.io/en/main/', None),
}
