# Use this for mapping to external links
extlinks = {
    'incf_collection': ('https://training.incf.org/collection/neurodata-without-borders-neurophysiology-nwbn', '%s'),
    'nwb_extension_git': ('https://github.com/nwb-extensions/%s', '%s'),
    'ndx-catalog': ('https://nwb-extensions.github.io/', '%s'),
    'pynwb-issue': ('https://github.com/NeurodataWithoutBorders/pynwb/issues/%s', 'pynwb#%s'),
    'nwb2-biorxiv': ('https://www.biorxiv.org/content/10.1101/523035v1',''),
    'nwb2-biorxiv-pdf': ('https://www.biorxiv.org/content/biorxiv/early/2019/01/17/523035.full.pdf','%s'),
    'allen-cell-type-atlas': ('http://celltypes.brain-map.org/', ''),
    'api-python': ('https://neurodatawithoutborders.github.io/api-python/build/html/api_usage.html', '%s'),
    'pynwb-src': ('https://github.com/NeurodataWithoutBorders/pynwb/', '%s'),
    'pynwb-docs': ('https://pynwb.readthedocs.io/en/stable/', '%s'),
    'hdmf-docs': ('https://hdmf.readthedocs.io/en/stable/', '%s'),
    'hdmf-src': ('https://github.com/hdmf-dev/hdmf', '%s'),
    'hdmf-specification-language': ('https://hdmf-schema-language.readthedocs.io/en/latest/', '%s'),
    'matnwb-src': ('https://github.com/NeurodataWithoutBorders/matnwb/', '%s'),
    'matnwb-docs': ('https://neurodatawithoutborders.github.io/matnwb/', '%s'),
    'neuroconv-docs': ('https://neuroconv.readthedocs.io/en/main/', '%s'),
    'neuroconv-src': ('https://github.com/catalystneuro/neuroconv', '%s'),
    'nwbinspector-docs': ('https://nwbinspector.readthedocs.io/en/dev/', '%s'),
    'ndx-template-docs': ('https://github.com/nwb-extensions/ndx-template', '%s'),
    'ndx-template-src': ('https://github.com/nwb-extensions/ndx-template', '%s'),
    'ndx-catalog-github-org': ('https://github.com/nwb-extensions/', '%s'),
    'hdmf-docutils-docs': ('https://github.com/hdmf-dev/hdmf-docutils', '%s'),
    'hdmf-docutils-src': ('https://github.com/hdmf-dev/hdmf-docutils', '%s'),
    'nwb-schema-language-docs': ('https://schema-language.readthedocs.io/en/latest/', '%s'),
    'nwb-storage-docs': ('https://nwb-storage.readthedocs.io/en/latest/', '%s'),
    'nwb-schema-docs': ('https://nwb-schema.readthedocs.io/en/latest/', '%s'),
    'nwb-schema-release-notes':('http://nwb-schema.readthedocs.io/en/latest/format_release_notes.html', '%s'),
    'nwb-schema-src': ('https://github.com/NeurodataWithoutBorders/nwb-schema', '%s'),
    'hdmf-common-schema-docs': ('https://hdmf-common-schema.readthedocs.io/en/stable/', '%s'),
    'hdmf-common-schema-src': ('https://github.com/hdmf-dev/hdmf-common-schema', '%s'),
    'hdmf-z-docs': ('https://hdmf-zarr.readthedocs.io/en/latest/', '%s'),
    'hdmf-z-src': ('https://github.com/hdmf-dev/hdmf-zarr' ,'%s'),
    'nwb-github-org': ('https://github.com/NeurodataWithoutBorders', '%s'),
    'hdmf-github-org': ('https://github.com/hdmf-dev', '%s'),
    'nwb-widgets-docs': ('https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets', '%s'),
    'nwb-widgets-src': ('https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets', '%s'),
    'caiman-docs': ('https://caiman.readthedocs.io/en/master/', '%s'),
    'hdf5': ('https://www.hdfgroup.org/solutions/hdf5/','%s'),
    'zarr': ('https://zarr.readthedocs.io/en/stable/', '%s'),
    'nix': ('https://g-node.github.io/nix/', '%s'),
    'bids': ('https://bids.neuroimaging.io/', '%s'),
    'dandi': ('https://dandiarchive.org/', '%s'),
    'nwb-overview-src': ('https://github.com/NeurodataWithoutBorders/nwb-overview', '%s'),
    'nwb-main': ('https://www.nwb.org/', '%s'),
    'nwb-helpdesk': ('https://github.com/dandi/helpdesk/discussions', '%s'),
    'nwb-mailing-list': ('http://visitor.r20.constantcontact.com/manage/optin?v=001nQUq2GTjwCjZxK_V2'
                         '-6RLElLJO1HMVtoNLJ-wGyDCukZQZxu2AFJmNh6NS0_lGMsWc2w9hZpeNn74HuWdv5RtLX9qX0o0Hy1P0hOgMrkm2NoGAX3VoY25wx8HAtIZwredcCuM0nCUGodpvoaue3SzQ%3D%3D', '%s'),
    'datajoint': ('https://www.datajoint.org/', '%s'),
    'datajoint-elements': ('https://www.datajoint.com/elements', '%s'),
}

# Use this for mapping for links to commonly used documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
    'h5py': ('https://docs.h5py.org/en/latest/', None),
    'hdmf': ('https://hdmf.readthedocs.io/en/stable/', None),
    'hdmf-z': ('https://hdmf-zarr.readthedocs.io/en/latest/', None),
    'pynwb': ('https://pynwb.readthedocs.io/en/stable/', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
    'neuroconv': ('https://neuroconv.readthedocs.io/en/main/', None),
    "nwb-schema": ("https://nwb-schema.readthedocs.io/en/latest/", None),
    "hdmf-common-schema": ("https://hdmf-common-schema.readthedocs.io/en/stable/", None),
}
