name: Testing External Links
on:
  schedule:
    - cron: '0 5 * * 0'  # every Sunday at 05:00 UTC (midnight EST)
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing External Links
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install sphinx Dependencies
        run: pip install -r requirements.txt
      - name: Test External Links
        run: sphinx-build -b linkcheck ./docs/source ./test_build

